<WeatherWidget>:
    orientation: 'horizontal'
    padding: 10
    spacing: 10
    on_press:
        app.root.current = 'weather_screen'
    Label:
        text: "test"
    Label:
        text: "test 2"

<WeatherScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'This is the weather screen'
        Button:
            text: 'Back to Main Screen'
            on_release: app.root.current = 'main'
